// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "alhikmah-attendance-api/internal/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// AttendanceRepository is an autogenerated mock type for the AttendanceRepository type
type AttendanceRepository struct {
	mock.Mock
}

// GetByClassAndDate provides a mock function with given fields: classID, date
func (_m *AttendanceRepository) GetByClassAndDate(classID string, date time.Time) ([]*domain.Attendance, error) {
	ret := _m.Called(classID, date)

	if len(ret) == 0 {
		panic("no return value specified for GetByClassAndDate")
	}

	var r0 []*domain.Attendance
	var r1 error
	if rf, ok := ret.Get(0).(func(string, time.Time) ([]*domain.Attendance, error)); ok {
		return rf(classID, date)
	}
	if rf, ok := ret.Get(0).(func(string, time.Time) []*domain.Attendance); ok {
		r0 = rf(classID, date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Attendance)
		}
	}

	if rf, ok := ret.Get(1).(func(string, time.Time) error); ok {
		r1 = rf(classID, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *AttendanceRepository) GetByID(id string) (*domain.Attendance, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Attendance
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Attendance, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Attendance); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Attendance)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkAttendance provides a mock function with given fields: attendance
func (_m *AttendanceRepository) MarkAttendance(attendance *domain.Attendance) error {
	ret := _m.Called(attendance)

	if len(ret) == 0 {
		panic("no return value specified for MarkAttendance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Attendance) error); ok {
		r0 = rf(attendance)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateAttendance provides a mock function with given fields: attendance, audit
func (_m *AttendanceRepository) UpdateAttendance(attendance *domain.Attendance, audit *domain.AttendanceAudit) error {
	ret := _m.Called(attendance, audit)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAttendance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Attendance, *domain.AttendanceAudit) error); ok {
		r0 = rf(attendance, audit)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAttendanceRepository creates a new instance of AttendanceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAttendanceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AttendanceRepository {
	mock := &AttendanceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
