// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "alhikmah-attendance-api/internal/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// AttendanceService is an autogenerated mock type for the AttendanceService type
type AttendanceService struct {
	mock.Mock
}

// GetByClassAndDate provides a mock function with given fields: classID, date, subject
func (_m *AttendanceService) GetByClassAndDate(classID string, date time.Time, subject string) ([]*domain.Attendance, error) {
	ret := _m.Called(classID, date, subject)

	if len(ret) == 0 {
		panic("no return value specified for GetByClassAndDate")
	}

	var r0 []*domain.Attendance
	var r1 error
	if rf, ok := ret.Get(0).(func(string, time.Time, string) ([]*domain.Attendance, error)); ok {
		return rf(classID, date, subject)
	}
	if rf, ok := ret.Get(0).(func(string, time.Time, string) []*domain.Attendance); ok {
		r0 = rf(classID, date, subject)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Attendance)
		}
	}

	if rf, ok := ret.Get(1).(func(string, time.Time, string) error); ok {
		r1 = rf(classID, date, subject)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetClassAttendanceForToday provides a mock function with given fields: classID, subject
func (_m *AttendanceService) GetClassAttendanceForToday(classID string, subject string) ([]*domain.Attendance, error) {
	ret := _m.Called(classID, subject)

	if len(ret) == 0 {
		panic("no return value specified for GetClassAttendanceForToday")
	}

	var r0 []*domain.Attendance
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) ([]*domain.Attendance, error)); ok {
		return rf(classID, subject)
	}
	if rf, ok := ret.Get(0).(func(string, string) []*domain.Attendance); ok {
		r0 = rf(classID, subject)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Attendance)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(classID, subject)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProcessManualAttendance provides a mock function with given fields: studentID, status, notes, teacherID, role, subject
func (_m *AttendanceService) ProcessManualAttendance(studentID string, status string, notes *string, teacherID string, role string, subject string) error {
	ret := _m.Called(studentID, status, notes, teacherID, role, subject)

	if len(ret) == 0 {
		panic("no return value specified for ProcessManualAttendance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, *string, string, string, string) error); ok {
		r0 = rf(studentID, status, notes, teacherID, role, subject)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProcessQRScan provides a mock function with given fields: nisn, teacherID, role, subject
func (_m *AttendanceService) ProcessQRScan(nisn string, teacherID string, role string, subject string) error {
	ret := _m.Called(nisn, teacherID, role, subject)

	if len(ret) == 0 {
		panic("no return value specified for ProcessQRScan")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string) error); ok {
		r0 = rf(nisn, teacherID, role, subject)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateManual provides a mock function with given fields: attendanceID, status, reason, changedBy
func (_m *AttendanceService) UpdateManual(attendanceID string, status string, reason string, changedBy string) error {
	ret := _m.Called(attendanceID, status, reason, changedBy)

	if len(ret) == 0 {
		panic("no return value specified for UpdateManual")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string) error); ok {
		r0 = rf(attendanceID, status, reason, changedBy)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAttendanceService creates a new instance of AttendanceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAttendanceService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AttendanceService {
	mock := &AttendanceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
