// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "alhikmah-attendance-api/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// ClassService is an autogenerated mock type for the ClassService type
type ClassService struct {
	mock.Mock
}

// Create provides a mock function with given fields: class
func (_m *ClassService) Create(class *domain.Class) error {
	ret := _m.Called(class)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Class) error); ok {
		r0 = rf(class)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: teacherID, academicYear, page, limit
func (_m *ClassService) GetAll(teacherID string, academicYear string, page int, limit int) ([]*domain.Class, int, error) {
	ret := _m.Called(teacherID, academicYear, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*domain.Class
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string, int, int) ([]*domain.Class, int, error)); ok {
		return rf(teacherID, academicYear, page, limit)
	}
	if rf, ok := ret.Get(0).(func(string, string, int, int) []*domain.Class); ok {
		r0 = rf(teacherID, academicYear, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Class)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, int, int) int); ok {
		r1 = rf(teacherID, academicYear, page, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(string, string, int, int) error); ok {
		r2 = rf(teacherID, academicYear, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetByID provides a mock function with given fields: id
func (_m *ClassService) GetByID(id string) (*domain.Class, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Class
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Class, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Class); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Class)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SoftDelete provides a mock function with given fields: id
func (_m *ClassService) SoftDelete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: class
func (_m *ClassService) Update(class *domain.Class) error {
	ret := _m.Called(class)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Class) error); ok {
		r0 = rf(class)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewClassService creates a new instance of ClassService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClassService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClassService {
	mock := &ClassService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
