// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "alhikmah-attendance-api/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// ClassRepository is an autogenerated mock type for the ClassRepository type
type ClassRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: class
func (_m *ClassRepository) Create(class *domain.Class) error {
	ret := _m.Called(class)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Class) error); ok {
		r0 = rf(class)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: teacherID, academicYear, offset, limit
func (_m *ClassRepository) GetAll(teacherID string, academicYear string, offset int, limit int) ([]*domain.Class, int, error) {
	ret := _m.Called(teacherID, academicYear, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*domain.Class
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string, int, int) ([]*domain.Class, int, error)); ok {
		return rf(teacherID, academicYear, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(string, string, int, int) []*domain.Class); ok {
		r0 = rf(teacherID, academicYear, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Class)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, int, int) int); ok {
		r1 = rf(teacherID, academicYear, offset, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(string, string, int, int) error); ok {
		r2 = rf(teacherID, academicYear, offset, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetByID provides a mock function with given fields: id
func (_m *ClassRepository) GetByID(id string) (*domain.Class, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Class
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Class, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Class); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Class)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IsTeacherResponsibleForStudent provides a mock function with given fields: studentID, teacherID
func (_m *ClassRepository) IsTeacherResponsibleForStudent(studentID string, teacherID string) (bool, error) {
	ret := _m.Called(studentID, teacherID)

	if len(ret) == 0 {
		panic("no return value specified for IsTeacherResponsibleForStudent")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return rf(studentID, teacherID)
	}
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(studentID, teacherID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(studentID, teacherID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SoftDelete provides a mock function with given fields: id
func (_m *ClassRepository) SoftDelete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: class
func (_m *ClassRepository) Update(class *domain.Class) error {
	ret := _m.Called(class)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Class) error); ok {
		r0 = rf(class)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewClassRepository creates a new instance of ClassRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClassRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClassRepository {
	mock := &ClassRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
