// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "alhikmah-attendance-api/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// ClassTeacherRepository is an autogenerated mock type for the ClassTeacherRepository type
type ClassTeacherRepository struct {
	mock.Mock
}

// Assign provides a mock function with given fields: ct
func (_m *ClassTeacherRepository) Assign(ct *domain.ClassTeacher) error {
	ret := _m.Called(ct)

	if len(ret) == 0 {
		panic("no return value specified for Assign")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.ClassTeacher) error); ok {
		r0 = rf(ct)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByClassID provides a mock function with given fields: classID
func (_m *ClassTeacherRepository) GetByClassID(classID string) ([]*domain.ClassTeacher, error) {
	ret := _m.Called(classID)

	if len(ret) == 0 {
		panic("no return value specified for GetByClassID")
	}

	var r0 []*domain.ClassTeacher
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*domain.ClassTeacher, error)); ok {
		return rf(classID)
	}
	if rf, ok := ret.Get(0).(func(string) []*domain.ClassTeacher); ok {
		r0 = rf(classID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.ClassTeacher)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(classID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByTeacherID provides a mock function with given fields: teacherID
func (_m *ClassTeacherRepository) GetByTeacherID(teacherID string) ([]*domain.ClassTeacher, error) {
	ret := _m.Called(teacherID)

	if len(ret) == 0 {
		panic("no return value specified for GetByTeacherID")
	}

	var r0 []*domain.ClassTeacher
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*domain.ClassTeacher, error)); ok {
		return rf(teacherID)
	}
	if rf, ok := ret.Get(0).(func(string) []*domain.ClassTeacher); ok {
		r0 = rf(teacherID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.ClassTeacher)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(teacherID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSubjectAssignments provides a mock function with given fields: teacherID
func (_m *ClassTeacherRepository) GetSubjectAssignments(teacherID string) ([]*domain.ClassTeacher, error) {
	ret := _m.Called(teacherID)

	if len(ret) == 0 {
		panic("no return value specified for GetSubjectAssignments")
	}

	var r0 []*domain.ClassTeacher
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*domain.ClassTeacher, error)); ok {
		return rf(teacherID)
	}
	if rf, ok := ret.Get(0).(func(string) []*domain.ClassTeacher); ok {
		r0 = rf(teacherID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.ClassTeacher)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(teacherID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Unassign provides a mock function with given fields: teacherID, classID, subject
func (_m *ClassTeacherRepository) Unassign(teacherID string, classID string, subject string) error {
	ret := _m.Called(teacherID, classID, subject)

	if len(ret) == 0 {
		panic("no return value specified for Unassign")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(teacherID, classID, subject)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewClassTeacherRepository creates a new instance of ClassTeacherRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClassTeacherRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClassTeacherRepository {
	mock := &ClassTeacherRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
