// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "alhikmah-attendance-api/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// EnrollmentService is an autogenerated mock type for the EnrollmentService type
type EnrollmentService struct {
	mock.Mock
}

// Enroll provides a mock function with given fields: studentID, classID, academicYear
func (_m *EnrollmentService) Enroll(studentID string, classID string, academicYear string) error {
	ret := _m.Called(studentID, classID, academicYear)

	if len(ret) == 0 {
		panic("no return value specified for Enroll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(studentID, classID, academicYear)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetActiveByClassID provides a mock function with given fields: classID
func (_m *EnrollmentService) GetActiveByClassID(classID string) ([]*domain.StudentEnrollment, error) {
	ret := _m.Called(classID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveByClassID")
	}

	var r0 []*domain.StudentEnrollment
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*domain.StudentEnrollment, error)); ok {
		return rf(classID)
	}
	if rf, ok := ret.Get(0).(func(string) []*domain.StudentEnrollment); ok {
		r0 = rf(classID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.StudentEnrollment)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(classID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetActiveByStudentID provides a mock function with given fields: studentID
func (_m *EnrollmentService) GetActiveByStudentID(studentID string) (*domain.StudentEnrollment, error) {
	ret := _m.Called(studentID)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveByStudentID")
	}

	var r0 *domain.StudentEnrollment
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.StudentEnrollment, error)); ok {
		return rf(studentID)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.StudentEnrollment); ok {
		r0 = rf(studentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.StudentEnrollment)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(studentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHistoryByStudentID provides a mock function with given fields: studentID
func (_m *EnrollmentService) GetHistoryByStudentID(studentID string) ([]*domain.StudentEnrollment, error) {
	ret := _m.Called(studentID)

	if len(ret) == 0 {
		panic("no return value specified for GetHistoryByStudentID")
	}

	var r0 []*domain.StudentEnrollment
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*domain.StudentEnrollment, error)); ok {
		return rf(studentID)
	}
	if rf, ok := ret.Get(0).(func(string) []*domain.StudentEnrollment); ok {
		r0 = rf(studentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.StudentEnrollment)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(studentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PromoteClass provides a mock function with given fields: items, academicYear
func (_m *EnrollmentService) PromoteClass(items []domain.PromoteItem, academicYear string) (int, error) {
	ret := _m.Called(items, academicYear)

	if len(ret) == 0 {
		panic("no return value specified for PromoteClass")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func([]domain.PromoteItem, string) (int, error)); ok {
		return rf(items, academicYear)
	}
	if rf, ok := ret.Get(0).(func([]domain.PromoteItem, string) int); ok {
		r0 = rf(items, academicYear)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func([]domain.PromoteItem, string) error); ok {
		r1 = rf(items, academicYear)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransferStudent provides a mock function with given fields: studentID, fromClassID, toClassID, academicYear
func (_m *EnrollmentService) TransferStudent(studentID string, fromClassID string, toClassID string, academicYear string) error {
	ret := _m.Called(studentID, fromClassID, toClassID, academicYear)

	if len(ret) == 0 {
		panic("no return value specified for TransferStudent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string) error); ok {
		r0 = rf(studentID, fromClassID, toClassID, academicYear)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEnrollmentService creates a new instance of EnrollmentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEnrollmentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *EnrollmentService {
	mock := &EnrollmentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
