// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "alhikmah-attendance-api/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// ReportService is an autogenerated mock type for the ReportService type
type ReportService struct {
	mock.Mock
}

// GetDailyReport provides a mock function with given fields: classID, dateStr, forceRefresh, generatedBy
func (_m *ReportService) GetDailyReport(classID string, dateStr string, forceRefresh bool, generatedBy string) (*domain.DailyReport, error) {
	ret := _m.Called(classID, dateStr, forceRefresh, generatedBy)

	if len(ret) == 0 {
		panic("no return value specified for GetDailyReport")
	}

	var r0 *domain.DailyReport
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, bool, string) (*domain.DailyReport, error)); ok {
		return rf(classID, dateStr, forceRefresh, generatedBy)
	}
	if rf, ok := ret.Get(0).(func(string, string, bool, string) *domain.DailyReport); ok {
		r0 = rf(classID, dateStr, forceRefresh, generatedBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DailyReport)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, bool, string) error); ok {
		r1 = rf(classID, dateStr, forceRefresh, generatedBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMonthlyReport provides a mock function with given fields: classID, monthStr, forceRefresh, generatedBy
func (_m *ReportService) GetMonthlyReport(classID string, monthStr string, forceRefresh bool, generatedBy string) (*domain.MonthlyReport, error) {
	ret := _m.Called(classID, monthStr, forceRefresh, generatedBy)

	if len(ret) == 0 {
		panic("no return value specified for GetMonthlyReport")
	}

	var r0 *domain.MonthlyReport
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, bool, string) (*domain.MonthlyReport, error)); ok {
		return rf(classID, monthStr, forceRefresh, generatedBy)
	}
	if rf, ok := ret.Get(0).(func(string, string, bool, string) *domain.MonthlyReport); ok {
		r0 = rf(classID, monthStr, forceRefresh, generatedBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MonthlyReport)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, bool, string) error); ok {
		r1 = rf(classID, monthStr, forceRefresh, generatedBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSemesterReport provides a mock function with given fields: classID, academicYear, semester, forceRefresh, generatedBy
func (_m *ReportService) GetSemesterReport(classID string, academicYear string, semester int, forceRefresh bool, generatedBy string) (*domain.SemesterReport, error) {
	ret := _m.Called(classID, academicYear, semester, forceRefresh, generatedBy)

	if len(ret) == 0 {
		panic("no return value specified for GetSemesterReport")
	}

	var r0 *domain.SemesterReport
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, int, bool, string) (*domain.SemesterReport, error)); ok {
		return rf(classID, academicYear, semester, forceRefresh, generatedBy)
	}
	if rf, ok := ret.Get(0).(func(string, string, int, bool, string) *domain.SemesterReport); ok {
		r0 = rf(classID, academicYear, semester, forceRefresh, generatedBy)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.SemesterReport)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, int, bool, string) error); ok {
		r1 = rf(classID, academicYear, semester, forceRefresh, generatedBy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStudentReport provides a mock function with given fields: studentID, startDate, endDate
func (_m *ReportService) GetStudentReport(studentID string, startDate string, endDate string) (*domain.StudentReport, error) {
	ret := _m.Called(studentID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetStudentReport")
	}

	var r0 *domain.StudentReport
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (*domain.StudentReport, error)); ok {
		return rf(studentID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) *domain.StudentReport); ok {
		r0 = rf(studentID, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.StudentReport)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(studentID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewReportService creates a new instance of ReportService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportService {
	mock := &ReportService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
