services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alhikmah_api
    env_file: .env
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - PORT=8080
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:-supersecretrefreshjwttoken}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - attendance-network

  db:
    image: postgres:17-alpine
    container_name: alhikmah_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-alhikmah_db}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - attendance-network

volumes:
  pgdata:

networks:
  attendance-network:
    driver: bridge
