// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	json "encoding/json"

	mock "github.com/stretchr/testify/mock"
)

// ReportCacheRepository is an autogenerated mock type for the ReportCacheRepository type
type ReportCacheRepository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: reportType, classID, periodStart, periodEnd
func (_m *ReportCacheRepository) Delete(reportType string, classID string, periodStart string, periodEnd string) error {
	ret := _m.Called(reportType, classID, periodStart, periodEnd)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string) error); ok {
		r0 = rf(reportType, classID, periodStart, periodEnd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: reportType, classID, periodStart, periodEnd
func (_m *ReportCacheRepository) Get(reportType string, classID string, periodStart string, periodEnd string) (json.RawMessage, error) {
	ret := _m.Called(reportType, classID, periodStart, periodEnd)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, string) (json.RawMessage, error)); ok {
		return rf(reportType, classID, periodStart, periodEnd)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string) json.RawMessage); ok {
		r0 = rf(reportType, classID, periodStart, periodEnd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string, string) error); ok {
		r1 = rf(reportType, classID, periodStart, periodEnd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: reportType, classID, periodStart, periodEnd, generatedBy, data
func (_m *ReportCacheRepository) Set(reportType string, classID string, periodStart string, periodEnd string, generatedBy string, data json.RawMessage) error {
	ret := _m.Called(reportType, classID, periodStart, periodEnd, generatedBy, data)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, string, json.RawMessage) error); ok {
		r0 = rf(reportType, classID, periodStart, periodEnd, generatedBy, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewReportCacheRepository creates a new instance of ReportCacheRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportCacheRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportCacheRepository {
	mock := &ReportCacheRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
