// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "alhikmah-attendance-api/core/domain"

	mock "github.com/stretchr/testify/mock"
)

// ReportRepository is an autogenerated mock type for the ReportRepository type
type ReportRepository struct {
	mock.Mock
}

// GetAggregatedReportRaw provides a mock function with given fields: classID, startDate, endDate
func (_m *ReportRepository) GetAggregatedReportRaw(classID string, startDate string, endDate string) ([]domain.MonthlyStatRaw, int, error) {
	ret := _m.Called(classID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetAggregatedReportRaw")
	}

	var r0 []domain.MonthlyStatRaw
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string, string) ([]domain.MonthlyStatRaw, int, error)); ok {
		return rf(classID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) []domain.MonthlyStatRaw); ok {
		r0 = rf(classID, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.MonthlyStatRaw)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) int); ok {
		r1 = rf(classID, startDate, endDate)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(string, string, string) error); ok {
		r2 = rf(classID, startDate, endDate)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetClassName provides a mock function with given fields: classID
func (_m *ReportRepository) GetClassName(classID string) (string, error) {
	ret := _m.Called(classID)

	if len(ret) == 0 {
		panic("no return value specified for GetClassName")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(classID)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(classID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(classID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDailyReportRaw provides a mock function with given fields: classID, dateStr
func (_m *ReportRepository) GetDailyReportRaw(classID string, dateStr string) ([]domain.DailyRecordRaw, error) {
	ret := _m.Called(classID, dateStr)

	if len(ret) == 0 {
		panic("no return value specified for GetDailyReportRaw")
	}

	var r0 []domain.DailyRecordRaw
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) ([]domain.DailyRecordRaw, error)); ok {
		return rf(classID, dateStr)
	}
	if rf, ok := ret.Get(0).(func(string, string) []domain.DailyRecordRaw); ok {
		r0 = rf(classID, dateStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DailyRecordRaw)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(classID, dateStr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStudentReportRaw provides a mock function with given fields: studentID, startDate, endDate
func (_m *ReportRepository) GetStudentReportRaw(studentID string, startDate string, endDate string) ([]domain.StudentReportRecord, error) {
	ret := _m.Called(studentID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetStudentReportRaw")
	}

	var r0 []domain.StudentReportRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) ([]domain.StudentReportRecord, error)); ok {
		return rf(studentID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) []domain.StudentReportRecord); ok {
		r0 = rf(studentID, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.StudentReportRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(studentID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTrendRaw provides a mock function with given fields: classID, startDate, endDate
func (_m *ReportRepository) GetTrendRaw(classID string, startDate string, endDate string) ([]domain.TrendRaw, error) {
	ret := _m.Called(classID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetTrendRaw")
	}

	var r0 []domain.TrendRaw
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) ([]domain.TrendRaw, error)); ok {
		return rf(classID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) []domain.TrendRaw); ok {
		r0 = rf(classID, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.TrendRaw)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(classID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewReportRepository creates a new instance of ReportRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportRepository {
	mock := &ReportRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
