// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "alhikmah-attendance-api/core/domain"

	mock "github.com/stretchr/testify/mock"
)

// StudentService is an autogenerated mock type for the StudentService type
type StudentService struct {
	mock.Mock
}

// Create provides a mock function with given fields: student
func (_m *StudentService) Create(student *domain.Student) error {
	ret := _m.Called(student)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Student) error); ok {
		r0 = rf(student)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateBulk provides a mock function with given fields: students
func (_m *StudentService) CreateBulk(students []*domain.Student) error {
	ret := _m.Called(students)

	if len(ret) == 0 {
		panic("no return value specified for CreateBulk")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]*domain.Student) error); ok {
		r0 = rf(students)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GenerateQRCodeData provides a mock function with given fields: nisn, fullName, className
func (_m *StudentService) GenerateQRCodeData(nisn string, fullName string, className string) string {
	ret := _m.Called(nisn, fullName, className)

	if len(ret) == 0 {
		panic("no return value specified for GenerateQRCodeData")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = rf(nisn, fullName, className)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetAll provides a mock function with given fields: teacherID, isActive, classID, search, page, limit
func (_m *StudentService) GetAll(teacherID string, isActive *bool, classID string, search string, page int, limit int) ([]*domain.Student, int, error) {
	ret := _m.Called(teacherID, isActive, classID, search, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*domain.Student
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(string, *bool, string, string, int, int) ([]*domain.Student, int, error)); ok {
		return rf(teacherID, isActive, classID, search, page, limit)
	}
	if rf, ok := ret.Get(0).(func(string, *bool, string, string, int, int) []*domain.Student); ok {
		r0 = rf(teacherID, isActive, classID, search, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Student)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *bool, string, string, int, int) int); ok {
		r1 = rf(teacherID, isActive, classID, search, page, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(string, *bool, string, string, int, int) error); ok {
		r2 = rf(teacherID, isActive, classID, search, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetByClassID provides a mock function with given fields: classID
func (_m *StudentService) GetByClassID(classID string) ([]*domain.Student, error) {
	ret := _m.Called(classID)

	if len(ret) == 0 {
		panic("no return value specified for GetByClassID")
	}

	var r0 []*domain.Student
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*domain.Student, error)); ok {
		return rf(classID)
	}
	if rf, ok := ret.Get(0).(func(string) []*domain.Student); ok {
		r0 = rf(classID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Student)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(classID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *StudentService) GetByID(id string) (*domain.Student, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Student
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.Student, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.Student); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Student)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SoftDelete provides a mock function with given fields: id
func (_m *StudentService) SoftDelete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for SoftDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: student
func (_m *StudentService) Update(student *domain.Student) error {
	ret := _m.Called(student)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Student) error); ok {
		r0 = rf(student)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStudentService creates a new instance of StudentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStudentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *StudentService {
	mock := &StudentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
